### PR TITLE
fix redhat logo path to make it show up again

### PR DESCRIPTION
**Pull request by robyduck**
See webticket #389.
https://fedorahosted.org/fedora-websites/ticket/389

### CODE REVIEW

**Comment by cydrobolt** [comment]
Thanks @robyduck!

**Comment by pypingou** [comment]
@cydrobolt was there a review done of this PR?

Not that the change looks bad but it looks like you opened it and two hours later merged it yourself without anyone reviewing it,

**Comment by robyduck** [comment]
@pypingou no, I opened it, not cydrobolt. And it's just a link fix, nothing to review or to be worried about, IMHO.

**Comment by pypingou** [comment]
Oh sorry, somehow I messed up the two avatars, sorry @cydrobolt and thanks for the review :)

**Pull request merged**
