### PR TITLE
Also retrieve trivial bugs

### PR DESCRIPTION
**Pull request by sanjayankur31**
https://fedoraproject.org/wiki/Package_Review_Process#The_Whiteboard

says that review tickets that are trivial to review should be marked
with "trivial" in the whiteboard. These are ideal for newbies to get
started with. They should also be in the easyfix list.

### CODE REVIEW

**Comment by pypingou** [comment]
Hm, these are package review, to which it is a little harder to contribute with an impact if you are not already a member of the packager group.
Won't this be frustrating for new comers if they spend time reviewing packages with little impact since they can't approve them?

**Comment by sanjayankur31** [comment]
I brought this up on the devel ML, and the one reply I got thinks it's a perfectly good idea. Could we please merge this and update the easyfix list? We'll then work on increasing awareness of the "easyfix" and "trivial" keywords etc. 

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/PMWE544CNZ2EFKY4QP3TVGRD4ZT7TWNC/

**Comment by sanjayankur31** [comment]
Please note that as documented, "trivial" tickets are specially marked for new people looking for easy tickets to review. So they target prospective contributors looking to do unofficial reviews, and this is very much in line with Easyfix.

**Comment by pypingou** [comment]
Looks good to me, we should get it in :)

**Comment by sanjayankur31** [comment]
Awesome---who do I poke to review and merge this request? :)

**Comment by pypingou** [comment]
me :)

**Comment by sanjayankur31** [comment]
Yay! Thanks! :)

**Pull request merged**
